[tool.black]
line-length = 88
target-version = ['py313']  # or whatever Python version you're using
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | \.migrations
  | \.venv
  | env
  | build
  | dist
  | /venv/        |   # virtual-env
  | /node_modules/
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true